### ISSUE TITLE
代码好坑啊

### ISSUE THREAD

**Issue by wusp1994** [Peerless-man/vue3-blog#2]
安装完成，运行报错：
> pure-admin-thin@3.9.7 dev D:\wu-pro\vue3-blog\blog-v3-admin
/dep-41cf5ffd.js:66189:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async resolveConfig (file:///D:/wu-pro/vue3-blog/blog-v3-admin/node_modules/.pnpm/vite@4.5.3_@types+node@18.19.34_sass@1.77.5_terser@5.31.1/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:65782:28)
    at async _createServer (file:///D:/wu-pro/vue3-blog/blog-v3-admin/node_modules/.pnpm/vite@4.5.3_@types+node@18.19.34_sass@1.77.5_terser@5.31.1/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:65051:20)
    at async CAC.<anonymous> (file:///D:/wu-pro/vue3-blog/blog-v3-admin/node_modules/.pnpm/vite@4.5.3_@types+node@18.19.34_sass@1.77.5_terser@5.31.1/node_modules/vite/dist/node/cli.js:763:24)
 ELIFECYCLE  Command failed with exit code 1.

**Comment by mrzym99** [comment]
使用 pnpm run serve 试试呢

**Comment by wusp1994** [comment]
微信号是：Wusp1994 ，QQ ：812190146
